name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests and build
        run: npm run ci

      - name: Create package
        run: npm pack

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## Installation

            ```bash
            npm install -g olx-mcp
            ```

            ## Claude Desktop Configuration

            Add to your `claude_desktop_config.json`:

            ```json
            {
              "mcpServers": {
                "olx-mcp": {
                  "command": "olx-mcp"
                }
              }
            }
            ```

            ## What's Changed

            - See commit history for detailed changes
            - Fully compatible with Claude Desktop
            - Supports all 5 OLX domains (PT, PL, BG, RO, UA)

      - name: Upload package as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./olx-mcp-1.0.0.tgz
          asset_name: olx-mcp-1.0.0.tgz
          asset_content_type: application/gzip

  # Run package locally before publishing
  test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build and pack
        run: |
          npm run build
          npm pack

      - name: Test global installation
        run: |
          npm install -g ./olx-mcp-*.tgz
          which olx-mcp
          olx-mcp --version || echo "Binary installed successfully"